default_language_version:
  python: python3.13
default_stages: [pre-commit]
exclude: "^docs/"
minimum_pre_commit_version: "4.3.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        exclude: |
          (?x)^(
            .vscode/.*|
            tsconfig.json|
            tsconfig.app.json|
            tsconfig.node.json
          )$
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

# Sets up `.pre-commit-ci.yaml` to ensure pre-commit dependencies stay up to date.
ci:
  autoupdate_schedule: quarterly
  skip: []
  submodules: false
